### ISSUE TITLE
Double / Abs(sin) in frequency using Pytta with electromagnetic filed excitation

### ISSUE THREAD

**Issue by labodezao** [PyTTAmaster/PyTTa#32]
Hi here :) 

I use Pyyta for vibrational analysis of free reeds in iron (musical acoustic) and the machanical excitation is made thanks to a magnetic fields generated with a custom solenoid I made for thze occasion.
This magnetic field is not taking into account the polarisation my tension generated with my soundcard and Amplified with an proper amp so the frequency of the excitation is double of the signal generated by Pyyta, whereas the accelerometer used as sensors see the real frequency.

Even if I have this factor two, I get a shifted curve of my resonnant pike when I compare the measure I made with a Signal generor manually.

Do you have any idea / solution to have my curves not shifter ?
Should I need to use loopback signal to improve my results ?

Thanks a lot in advance !

**Comment by Chum4k3r** [comment]
This may occur due to an incompatible sampling rate, as stated on #31. Please, try out the suggestions on that issue and update us with your discoveries.

**Comment by labodezao** [comment]
Hi :)
My question is to find a solution to have the possibily to double actually the frequency label by two actually because when I excite the system at 40 Hz, the excitating force operate at 80 Hz because the electromagnets doesn't care about the electrical polarity. So the real excitation is like abs(sin(ft)) 
![image](https://user-images.githubusercontent.com/48204601/101616587-d22cbd80-3a0f-11eb-8967-03b356609257.png)

**Comment by Chum4k3r** [comment]
Then you just need to adjust how you see the plot? Have you tried to send your excitation signal as an absolute of the generated? From the other issue I know your are using a sine sweep, so you can make it a custom abs(sin(f(t)t)).

`mysweep.timeSignal = np.abs(mysweep.timeSignal)`

This will make the excitation waveform look like the actual excitation performed by your solenoid, thus the response might be more likely to what you expect.

**Comment by labodezao** [comment]
Oh Good ! I did not know that Tip !

Thanks ❤️ ❤️

**Comment by labodezao** [comment]
That was a good Idea, but taking the abs() for the sweep time signal is not working.
This make really weird stuff and that does not change the frequency array by two. 
I try to find out where the frequency vector is stored in the frf Object ?

Thanks

**Comment by Chum4k3r** [comment]
Then it is the `med1.IR.freqVector`.
Also, pay attention to the`.IR.freqMin` and `.IR.freqMax` , as these are used to generate the plot limits.
