### ISSUE TITLE
PyTTa licensing

### ISSUE THREAD

**Issue by Chum4k3r** [PyTTAmaster/PyTTa#7]
Right now it is registered within setup.py file that PyTTa is distributed under the MIT license, but still there is no LICENSE file at the repository.

### Which license should be used?

The main choices are GPLv3, that ensures all software based on PyTTa must also be distributed under GPLv3, or MIT which is a full permissive license and requires only that the PyTTa package is redistributed under the same license.

In my opinion we can go with MIT.

**Comment by mtslazarin** [comment]
agree
